// flow-typed signature: 76b5acfa821ade8a506a9a456f6d2b27
// flow-typed version: <<STUB>>/react-router_v6.0.0-beta.0/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/main' {
  declare module.exports: any;
}

declare module 'react-router/react-router.development' {
  declare module.exports: any;
}

declare module 'react-router/react-router.production.min' {
  declare module.exports: any;
}

declare module 'react-router/umd/react-router.development' {
  declare module.exports: any;
}

declare module 'react-router/umd/react-router.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/index' {
  declare module.exports: $Exports<'react-router'>;
}
declare module 'react-router/index.js' {
  declare module.exports: $Exports<'react-router'>;
}
declare module 'react-router/main.js' {
  declare module.exports: $Exports<'react-router/main'>;
}
declare module 'react-router/react-router.development.js' {
  declare module.exports: $Exports<'react-router/react-router.development'>;
}
declare module 'react-router/react-router.production.min.js' {
  declare module.exports: $Exports<'react-router/react-router.production.min'>;
}
declare module 'react-router/umd/react-router.development.js' {
  declare module.exports: $Exports<'react-router/umd/react-router.development'>;
}
declare module 'react-router/umd/react-router.production.min.js' {
  declare module.exports: $Exports<'react-router/umd/react-router.production.min'>;
}
