// flow-typed signature: c490f471ed2792ac16506c0a031f3057
// flow-typed version: <<STUB>>/@styled-system/theme-get_v5.1.2/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@styled-system/theme-get'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@styled-system/theme-get' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@styled-system/theme-get/dist/index.esm' {
  declare module.exports: any;
}

declare module '@styled-system/theme-get/dist' {
  declare module.exports: any;
}

declare module '@styled-system/theme-get/src' {
  declare module.exports: any;
}

declare module '@styled-system/theme-get/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@styled-system/theme-get/dist/index.esm.js' {
  declare module.exports: $Exports<'@styled-system/theme-get/dist/index.esm'>;
}
declare module '@styled-system/theme-get/dist/index' {
  declare module.exports: $Exports<'@styled-system/theme-get/dist'>;
}
declare module '@styled-system/theme-get/dist/index.js' {
  declare module.exports: $Exports<'@styled-system/theme-get/dist'>;
}
declare module '@styled-system/theme-get/src/index' {
  declare module.exports: $Exports<'@styled-system/theme-get/src'>;
}
declare module '@styled-system/theme-get/src/index.js' {
  declare module.exports: $Exports<'@styled-system/theme-get/src'>;
}
declare module '@styled-system/theme-get/test/index' {
  declare module.exports: $Exports<'@styled-system/theme-get/test'>;
}
declare module '@styled-system/theme-get/test/index.js' {
  declare module.exports: $Exports<'@styled-system/theme-get/test'>;
}
